[main]
#function = rotate
# function = ToMp4
# function = ToWebp
# function = WebpTo
# function = Unzip
# function = Weather
# function = Detect
function = ExtractAudio
delAfterDone = true
[rotate]
direction = ToRight
# direction = ToLeft
[location]
src = /Volumes/Gloway720/26
pattern = webm;mp4;wmv;rm
dst = /Volumes/Gloway720/26
webpto = jpg
passwd = /Users/zen/Downloads/passwd.txt