[main]
# function = rotate
# function = ToMp4
# function = ToWebp
#function = WebpTo
function = Unzip
[rotate]
direction = ToRight
# direction = ToLeft
[location]
src = /Users/zen/Desktop/EverymacOScombined.zip
pattern = webp
dst = /Users/zen/Downloads/Downie
webpto = jpg
passwd = /Users/zen/Downloads/passwd.txt